name: yarn2nix
version: 0.5.0
github: Profpatsch/yarn2nix
license: MIT
license-file: LICENSE
synopsis: Convert yarn.lock files to nix expressions
author: Profpatsch
maintainer: mail@profpatsch.de
category: Distribution, Nix

ghc-options:
  - -Wall

dependencies:
  - aeson >= 1.0 && < 1.3
  - ansi-wl-pprint == 0.6.*
  - async-pool == 0.9.*
  - base == 4.*
  - bytestring == 0.10.*
  - containers >= 0.5 && < 0.7
  - data-fix >= 0.0.7 && < 0.1
  - directory == 1.3.*
  - either == 4.4.*
  - filepath == 1.4.*
  - hnix == 0.3.*
  - mtl == 2.2.*
  - process == 1.4.*
  - protolude == 0.1.*
  - regex-tdfa == 1.2.*
  - regex-tdfa-text == 1.0.0.*
  - stm == 2.4.*
  - text == 1.2.*
  - unordered-containers == 0.2.*
  - yarn-lock == 0.4.*

library:
  source-dirs: src

executables:
  yarn2nix:
    main: Main.hs
    dependencies:
      - yarn2nix
  setup-node-package-paths:
    main: SetupNodePackagePaths.hs
    dependencies:
      - optparse-applicative == 0.13.*
      - unix == 2.7.*
      - yarn2nix

tests:
  yarn2nix-tests:
    main: Test.hs
    source-dirs: tests
    dependencies:
      - neat-interpolation == 0.3.*
      - protolude == 0.1.*
      - tasty == 0.11.*
      - tasty-hunit == 0.9.*
      - tasty-quickcheck == 0.8.*
      - tasty-th == 0.1.7.*
      - yarn2nix