name: yarn2nix
version: 0.1.0
github: Profpatsch/yarn2nix
license: MIT
license-file: LICENSE
synopsis: Convert yarn.lock files to nix expressions
author: Profpatsch
maintainer: mail@profpatsch.de
category: Distribution, Nix

ghc-options:
  - -Wall

dependencies:
  - base == 4.*
  - yarn-lock == 0.4.*
  - aeson >= 1.0
  - async-pool == 0.9.*
  - bytestring
  - containers
  - directory >= 1.2
  - filepath
  - unordered-containers
  - mtl
  - text
  - protolude >= 0.1
  - hnix >= 0.3
  - ansi-wl-pprint
  - regex-tdfa == 1.2.*
  - regex-tdfa-text == 1.0.0.*
  - data-fix
  - process
  - either
  - stm

library:
  source-dirs: src

executables:
  yarn2nix:
    main: Main.hs
    dependencies:
      - yarn2nix
  setup-node-package-paths:
    main: SetupNodePackagePaths.hs
    dependencies:
      - yarn2nix
      - optparse-applicative == 0.13.*
      - unix

tests:
  yarn2nix-tests:
    main: Test.hs
    source-dirs: tests
    dependencies:
      - yarn2nix
      - tasty >= 0.11
      - tasty-th >= 0.1.7
      - tasty-hunit >= 0.9
      - tasty-quickcheck >= 0.8
      - protolude
      - neat-interpolation >= 0.3